### ISSUE TITLE
empty dataSource

### ISSUE THREAD

**Issue by yalagin** [gsongsong/antd-table-dnd-sortable#2]
how to fix the error when dataSource is an empty array?
you said "Shall be truthy to be draggable. I don't know why."
but what to do in production? set up a fake row and always check for the empty array ? =)

**Comment by sjeon87** [comment]
What is an error when dataSource is an empty array?

"Shall be truthy to be draggable" refers a value of a key of each item. If dataSource is empty, there is no item. I dont think there is a thing to worry.

Am I misunderstanding?

**Comment by yalagin** [comment]
https://codesandbox.io/s/antd-table-dnd-sortable-forked-2m6ru?file=/src/App.js
like this , I tried to fix it but there are a lot of errors. 
```js
  // const dataSourceRaw = new Array(5).fill({}).map((item, index) => ({
  //   // This will be transformed into `data-row-key` of props.
  //   // Shall be truthy to be draggable. I don't know why.
  //   // To this end, index of number type is converted into string.
  //   key: index.toString()
  // }));
  const [dataSource, setDataSource] = useState([]);
  ```

    
![Снимок экрана 2021-10-05 в 12 53 05](https://user-images.githubusercontent.com/12879142/136001424-456b0fe6-fc59-41f4-90b1-51e84b33f6a4.png)

**Comment by sjeon87** [comment]
Oh, I missed this case.
~~203c668bfe9071c1f2378b5c8349e96d478bdc6e would fix.~~

**Comment by sjeon87** [comment]
Sorry. Check this out 2b5492dbb7011418165d88b369a2cf5154c6ca8a

Net diff: https://github.com/gsongsong/antd-table-dnd-sortable/compare/ca53ca5015c7c48879566864437b853f49dedbd7..2b5492dbb7011418165d88b369a2cf5154c6ca8a
